//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChungChi
    {
        public int IDChungChi { get; set; }
        public Nullable<int> IDKetQua { get; set; }
        public string SoVaoSo { get; set; }
        public string SoVanBang { get; set; }
    
        public virtual KetQua KetQua { get; set; }
    }
}
