//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachThuBai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhSachThuBai()
        {
            this.KetQuas = new HashSet<KetQua>();
        }
    
        public int IDThuBai { get; set; }
        public Nullable<int> IDThi { get; set; }
        public Nullable<double> DiemTN { get; set; }
        public Nullable<double> KichThuocWord { get; set; }
        public Nullable<double> KichThuocExcel { get; set; }
        public Nullable<double> KichThuocPpt { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DanhSachThi DanhSachThi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQua> KetQuas { get; set; }
    }
}
