//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoiDong
    {
        public int IDHoiDong { get; set; }
        public Nullable<int> IDGiaoVien { get; set; }
        public Nullable<int> IDDotThi { get; set; }
        public Nullable<int> IDNhiemVu { get; set; }
    
        public virtual DotThi DotThi { get; set; }
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual NhiemVu NhiemVu { get; set; }
    }
}
