//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LePhi
    {
        public int IDLePhi { get; set; }
        public Nullable<int> IDNoiDung { get; set; }
        public Nullable<int> IDNhuCau { get; set; }
        public Nullable<decimal> LePhi1 { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public System.DateTime DenNgay { get; set; }
    
        public virtual NhuCau NhuCau { get; set; }
        public virtual NoiDung NoiDung { get; set; }
    }
}
