//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCSDL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLThiCCEntities : DbContext
    {
        public QLThiCCEntities()
            : base("name=QLThiCCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChungChi> ChungChi { get; set; }
        public virtual DbSet<DanhSachThi> DanhSachThi { get; set; }
        public virtual DbSet<DanhSachThuBai> DanhSachThuBai { get; set; }
        public virtual DbSet<DotThi> DotThi { get; set; }
        public virtual DbSet<GiaoVien> GiaoVien { get; set; }
        public virtual DbSet<HoiDong> HoiDong { get; set; }
        public virtual DbSet<KetQua> KetQua { get; set; }
        public virtual DbSet<LePhi> LePhi { get; set; }
        public virtual DbSet<LePhiTest> LePhiTest { get; set; }
        public virtual DbSet<NhiemVu> NhiemVu { get; set; }
        public virtual DbSet<NhuCau> NhuCau { get; set; }
        public virtual DbSet<NoiDung> NoiDung { get; set; }
        public virtual DbSet<sysdiagram> sysdiagram { get; set; }
        public virtual DbSet<ThiSinh> ThiSinh { get; set; }
        public virtual DbSet<User> User { get; set; }
    
        public virtual int Sua_GiaoVien_ID(Nullable<int> idgiaovien, string ho, string ten, string donvi, string capbac)
        {
            var idgiaovienParameter = idgiaovien.HasValue ?
                new ObjectParameter("idgiaovien", idgiaovien) :
                new ObjectParameter("idgiaovien", typeof(int));
    
            var hoParameter = ho != null ?
                new ObjectParameter("ho", ho) :
                new ObjectParameter("ho", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            var capbacParameter = capbac != null ?
                new ObjectParameter("capbac", capbac) :
                new ObjectParameter("capbac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sua_GiaoVien_ID", idgiaovienParameter, hoParameter, tenParameter, donviParameter, capbacParameter);
        }
    
        public virtual int SuaTheoThiSinh(Nullable<int> idthisinh, string email, string ho, string ten, Nullable<System.DateTime> ngaysinh, Nullable<bool> gioitinh, string cmnd, string sdt, Nullable<int> idnhucau, Nullable<int> idnoidung, string trangthai)
        {
            var idthisinhParameter = idthisinh.HasValue ?
                new ObjectParameter("idthisinh", idthisinh) :
                new ObjectParameter("idthisinh", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var hoParameter = ho != null ?
                new ObjectParameter("ho", ho) :
                new ObjectParameter("ho", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh.HasValue ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(bool));
    
            var cmndParameter = cmnd != null ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var idnhucauParameter = idnhucau.HasValue ?
                new ObjectParameter("idnhucau", idnhucau) :
                new ObjectParameter("idnhucau", typeof(int));
    
            var idnoidungParameter = idnoidung.HasValue ?
                new ObjectParameter("idnoidung", idnoidung) :
                new ObjectParameter("idnoidung", typeof(int));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaTheoThiSinh", idthisinhParameter, emailParameter, hoParameter, tenParameter, ngaysinhParameter, gioitinhParameter, cmndParameter, sdtParameter, idnhucauParameter, idnoidungParameter, trangthaiParameter);
        }
    
        public virtual int Them_GiaoVien(string ho, string ten, string donvi, string capbac)
        {
            var hoParameter = ho != null ?
                new ObjectParameter("ho", ho) :
                new ObjectParameter("ho", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            var capbacParameter = capbac != null ?
                new ObjectParameter("capbac", capbac) :
                new ObjectParameter("capbac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Them_GiaoVien", hoParameter, tenParameter, donviParameter, capbacParameter);
        }
    
        public virtual int ThemTS(string email, string ho, string ten, Nullable<System.DateTime> ngaysinh, Nullable<bool> gioitinh, string cmnd, string std, Nullable<int> idnoidung, Nullable<int> idnhucau, string trangthai)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var hoParameter = ho != null ?
                new ObjectParameter("ho", ho) :
                new ObjectParameter("ho", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh.HasValue ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(bool));
    
            var cmndParameter = cmnd != null ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(string));
    
            var stdParameter = std != null ?
                new ObjectParameter("std", std) :
                new ObjectParameter("std", typeof(string));
    
            var idnoidungParameter = idnoidung.HasValue ?
                new ObjectParameter("idnoidung", idnoidung) :
                new ObjectParameter("idnoidung", typeof(int));
    
            var idnhucauParameter = idnhucau.HasValue ?
                new ObjectParameter("idnhucau", idnhucau) :
                new ObjectParameter("idnhucau", typeof(int));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemTS", emailParameter, hoParameter, tenParameter, ngaysinhParameter, gioitinhParameter, cmndParameter, stdParameter, idnoidungParameter, idnhucauParameter, trangthaiParameter);
        }
    
        public virtual int Xoa_GiaoVien_ID(Nullable<int> idgiaovien)
        {
            var idgiaovienParameter = idgiaovien.HasValue ?
                new ObjectParameter("idgiaovien", idgiaovien) :
                new ObjectParameter("idgiaovien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Xoa_GiaoVien_ID", idgiaovienParameter);
        }
    
        public virtual int XoaTheoMaThiSinh(Nullable<int> idthisinh)
        {
            var idthisinhParameter = idthisinh.HasValue ?
                new ObjectParameter("idthisinh", idthisinh) :
                new ObjectParameter("idthisinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaTheoMaThiSinh", idthisinhParameter);
        }
    
        public virtual int ChungChi_Delete(Nullable<int> idChungChi)
        {
            var idChungChiParameter = idChungChi.HasValue ?
                new ObjectParameter("IdChungChi", idChungChi) :
                new ObjectParameter("IdChungChi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChungChi_Delete", idChungChiParameter);
        }
    
        public virtual ObjectResult<ChungChi_Find_Result> ChungChi_Find(Nullable<bool> searchUsingOR, Nullable<int> idChungChi, Nullable<int> idKetQua, string soVaoSo, string soVanBang)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var idChungChiParameter = idChungChi.HasValue ?
                new ObjectParameter("IdChungChi", idChungChi) :
                new ObjectParameter("IdChungChi", typeof(int));
    
            var idKetQuaParameter = idKetQua.HasValue ?
                new ObjectParameter("IdKetQua", idKetQua) :
                new ObjectParameter("IdKetQua", typeof(int));
    
            var soVaoSoParameter = soVaoSo != null ?
                new ObjectParameter("SoVaoSo", soVaoSo) :
                new ObjectParameter("SoVaoSo", typeof(string));
    
            var soVanBangParameter = soVanBang != null ?
                new ObjectParameter("SoVanBang", soVanBang) :
                new ObjectParameter("SoVanBang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChungChi_Find_Result>("ChungChi_Find", searchUsingORParameter, idChungChiParameter, idKetQuaParameter, soVaoSoParameter, soVanBangParameter);
        }
    
        public virtual ObjectResult<ChungChi_Get_List_Result> ChungChi_Get_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChungChi_Get_List_Result>("ChungChi_Get_List");
        }
    
        public virtual ObjectResult<ChungChi_GetByIdChungChi_Result> ChungChi_GetByIdChungChi(Nullable<int> idChungChi)
        {
            var idChungChiParameter = idChungChi.HasValue ?
                new ObjectParameter("IdChungChi", idChungChi) :
                new ObjectParameter("IdChungChi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChungChi_GetByIdChungChi_Result>("ChungChi_GetByIdChungChi", idChungChiParameter);
        }
    
        public virtual ObjectResult<ChungChi_GetByIdKetQua_Result> ChungChi_GetByIdKetQua(Nullable<int> idKetQua)
        {
            var idKetQuaParameter = idKetQua.HasValue ?
                new ObjectParameter("IdKetQua", idKetQua) :
                new ObjectParameter("IdKetQua", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChungChi_GetByIdKetQua_Result>("ChungChi_GetByIdKetQua", idKetQuaParameter);
        }
    
        public virtual int ChungChi_GetPaged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChungChi_GetPaged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int ChungChi_Insert(ObjectParameter idChungChi, Nullable<int> idKetQua, string soVaoSo, string soVanBang)
        {
            var idKetQuaParameter = idKetQua.HasValue ?
                new ObjectParameter("IdKetQua", idKetQua) :
                new ObjectParameter("IdKetQua", typeof(int));
    
            var soVaoSoParameter = soVaoSo != null ?
                new ObjectParameter("SoVaoSo", soVaoSo) :
                new ObjectParameter("SoVaoSo", typeof(string));
    
            var soVanBangParameter = soVanBang != null ?
                new ObjectParameter("SoVanBang", soVanBang) :
                new ObjectParameter("SoVanBang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChungChi_Insert", idChungChi, idKetQuaParameter, soVaoSoParameter, soVanBangParameter);
        }
    
        public virtual int ChungChi_Update(Nullable<int> idChungChi, Nullable<int> idKetQua, string soVaoSo, string soVanBang)
        {
            var idChungChiParameter = idChungChi.HasValue ?
                new ObjectParameter("IdChungChi", idChungChi) :
                new ObjectParameter("IdChungChi", typeof(int));
    
            var idKetQuaParameter = idKetQua.HasValue ?
                new ObjectParameter("IdKetQua", idKetQua) :
                new ObjectParameter("IdKetQua", typeof(int));
    
            var soVaoSoParameter = soVaoSo != null ?
                new ObjectParameter("SoVaoSo", soVaoSo) :
                new ObjectParameter("SoVaoSo", typeof(string));
    
            var soVanBangParameter = soVanBang != null ?
                new ObjectParameter("SoVanBang", soVanBang) :
                new ObjectParameter("SoVanBang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChungChi_Update", idChungChiParameter, idKetQuaParameter, soVaoSoParameter, soVanBangParameter);
        }
    
        public virtual int DanhSachThi_Delete(Nullable<int> idThi)
        {
            var idThiParameter = idThi.HasValue ?
                new ObjectParameter("IdThi", idThi) :
                new ObjectParameter("IdThi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DanhSachThi_Delete", idThiParameter);
        }
    
        public virtual ObjectResult<DanhSachThi_Find_Result> DanhSachThi_Find(Nullable<bool> searchUsingOR, Nullable<int> idThi, Nullable<int> sbd, Nullable<int> idThiSinh, Nullable<int> idDotThi)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var idThiParameter = idThi.HasValue ?
                new ObjectParameter("IdThi", idThi) :
                new ObjectParameter("IdThi", typeof(int));
    
            var sbdParameter = sbd.HasValue ?
                new ObjectParameter("Sbd", sbd) :
                new ObjectParameter("Sbd", typeof(int));
    
            var idThiSinhParameter = idThiSinh.HasValue ?
                new ObjectParameter("IdThiSinh", idThiSinh) :
                new ObjectParameter("IdThiSinh", typeof(int));
    
            var idDotThiParameter = idDotThi.HasValue ?
                new ObjectParameter("IdDotThi", idDotThi) :
                new ObjectParameter("IdDotThi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhSachThi_Find_Result>("DanhSachThi_Find", searchUsingORParameter, idThiParameter, sbdParameter, idThiSinhParameter, idDotThiParameter);
        }
    
        public virtual ObjectResult<DanhSachThi_Get_List_Result> DanhSachThi_Get_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhSachThi_Get_List_Result>("DanhSachThi_Get_List");
        }
    
        public virtual ObjectResult<DanhSachThi_GetByIdDotThi_Result> DanhSachThi_GetByIdDotThi(Nullable<int> idDotThi)
        {
            var idDotThiParameter = idDotThi.HasValue ?
                new ObjectParameter("IdDotThi", idDotThi) :
                new ObjectParameter("IdDotThi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhSachThi_GetByIdDotThi_Result>("DanhSachThi_GetByIdDotThi", idDotThiParameter);
        }
    
        public virtual ObjectResult<DanhSachThi_GetByIdThi_Result> DanhSachThi_GetByIdThi(Nullable<int> idThi)
        {
            var idThiParameter = idThi.HasValue ?
                new ObjectParameter("IdThi", idThi) :
                new ObjectParameter("IdThi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhSachThi_GetByIdThi_Result>("DanhSachThi_GetByIdThi", idThiParameter);
        }
    
        public virtual ObjectResult<DanhSachThi_GetByIdThiSinh_Result> DanhSachThi_GetByIdThiSinh(Nullable<int> idThiSinh)
        {
            var idThiSinhParameter = idThiSinh.HasValue ?
                new ObjectParameter("IdThiSinh", idThiSinh) :
                new ObjectParameter("IdThiSinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhSachThi_GetByIdThiSinh_Result>("DanhSachThi_GetByIdThiSinh", idThiSinhParameter);
        }
    
        public virtual int DanhSachThi_GetPaged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DanhSachThi_GetPaged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int DanhSachThi_Insert(ObjectParameter idThi, Nullable<int> sbd, Nullable<int> idThiSinh, Nullable<int> idDotThi)
        {
            var sbdParameter = sbd.HasValue ?
                new ObjectParameter("Sbd", sbd) :
                new ObjectParameter("Sbd", typeof(int));
    
            var idThiSinhParameter = idThiSinh.HasValue ?
                new ObjectParameter("IdThiSinh", idThiSinh) :
                new ObjectParameter("IdThiSinh", typeof(int));
    
            var idDotThiParameter = idDotThi.HasValue ?
                new ObjectParameter("IdDotThi", idDotThi) :
                new ObjectParameter("IdDotThi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DanhSachThi_Insert", idThi, sbdParameter, idThiSinhParameter, idDotThiParameter);
        }
    
        public virtual int DanhSachThi_Update(Nullable<int> idThi, Nullable<int> sbd, Nullable<int> idThiSinh, Nullable<int> idDotThi)
        {
            var idThiParameter = idThi.HasValue ?
                new ObjectParameter("IdThi", idThi) :
                new ObjectParameter("IdThi", typeof(int));
    
            var sbdParameter = sbd.HasValue ?
                new ObjectParameter("Sbd", sbd) :
                new ObjectParameter("Sbd", typeof(int));
    
            var idThiSinhParameter = idThiSinh.HasValue ?
                new ObjectParameter("IdThiSinh", idThiSinh) :
                new ObjectParameter("IdThiSinh", typeof(int));
    
            var idDotThiParameter = idDotThi.HasValue ?
                new ObjectParameter("IdDotThi", idDotThi) :
                new ObjectParameter("IdDotThi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DanhSachThi_Update", idThiParameter, sbdParameter, idThiSinhParameter, idDotThiParameter);
        }
    
        public virtual int DanhSachThuBai_Delete(Nullable<int> idThuBai)
        {
            var idThuBaiParameter = idThuBai.HasValue ?
                new ObjectParameter("IdThuBai", idThuBai) :
                new ObjectParameter("IdThuBai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DanhSachThuBai_Delete", idThuBaiParameter);
        }
    
        public virtual ObjectResult<DanhSachThuBai_Find_Result> DanhSachThuBai_Find(Nullable<bool> searchUsingOR, Nullable<int> idThuBai, Nullable<int> idThi, Nullable<double> diemTn, Nullable<double> kichThuocWord, Nullable<double> kichThuocExcel, Nullable<double> kichThuocPpt)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var idThuBaiParameter = idThuBai.HasValue ?
                new ObjectParameter("IdThuBai", idThuBai) :
                new ObjectParameter("IdThuBai", typeof(int));
    
            var idThiParameter = idThi.HasValue ?
                new ObjectParameter("IdThi", idThi) :
                new ObjectParameter("IdThi", typeof(int));
    
            var diemTnParameter = diemTn.HasValue ?
                new ObjectParameter("DiemTn", diemTn) :
                new ObjectParameter("DiemTn", typeof(double));
    
            var kichThuocWordParameter = kichThuocWord.HasValue ?
                new ObjectParameter("KichThuocWord", kichThuocWord) :
                new ObjectParameter("KichThuocWord", typeof(double));
    
            var kichThuocExcelParameter = kichThuocExcel.HasValue ?
                new ObjectParameter("KichThuocExcel", kichThuocExcel) :
                new ObjectParameter("KichThuocExcel", typeof(double));
    
            var kichThuocPptParameter = kichThuocPpt.HasValue ?
                new ObjectParameter("KichThuocPpt", kichThuocPpt) :
                new ObjectParameter("KichThuocPpt", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhSachThuBai_Find_Result>("DanhSachThuBai_Find", searchUsingORParameter, idThuBaiParameter, idThiParameter, diemTnParameter, kichThuocWordParameter, kichThuocExcelParameter, kichThuocPptParameter);
        }
    
        public virtual ObjectResult<DanhSachThuBai_Get_List_Result> DanhSachThuBai_Get_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhSachThuBai_Get_List_Result>("DanhSachThuBai_Get_List");
        }
    
        public virtual ObjectResult<DanhSachThuBai_GetByIdThi_Result> DanhSachThuBai_GetByIdThi(Nullable<int> idThi)
        {
            var idThiParameter = idThi.HasValue ?
                new ObjectParameter("IdThi", idThi) :
                new ObjectParameter("IdThi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhSachThuBai_GetByIdThi_Result>("DanhSachThuBai_GetByIdThi", idThiParameter);
        }
    
        public virtual ObjectResult<DanhSachThuBai_GetByIdThuBai_Result> DanhSachThuBai_GetByIdThuBai(Nullable<int> idThuBai)
        {
            var idThuBaiParameter = idThuBai.HasValue ?
                new ObjectParameter("IdThuBai", idThuBai) :
                new ObjectParameter("IdThuBai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhSachThuBai_GetByIdThuBai_Result>("DanhSachThuBai_GetByIdThuBai", idThuBaiParameter);
        }
    
        public virtual int DanhSachThuBai_GetPaged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DanhSachThuBai_GetPaged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int DanhSachThuBai_Insert(ObjectParameter idThuBai, Nullable<int> idThi, Nullable<double> diemTn, Nullable<double> kichThuocWord, Nullable<double> kichThuocExcel, Nullable<double> kichThuocPpt)
        {
            var idThiParameter = idThi.HasValue ?
                new ObjectParameter("IdThi", idThi) :
                new ObjectParameter("IdThi", typeof(int));
    
            var diemTnParameter = diemTn.HasValue ?
                new ObjectParameter("DiemTn", diemTn) :
                new ObjectParameter("DiemTn", typeof(double));
    
            var kichThuocWordParameter = kichThuocWord.HasValue ?
                new ObjectParameter("KichThuocWord", kichThuocWord) :
                new ObjectParameter("KichThuocWord", typeof(double));
    
            var kichThuocExcelParameter = kichThuocExcel.HasValue ?
                new ObjectParameter("KichThuocExcel", kichThuocExcel) :
                new ObjectParameter("KichThuocExcel", typeof(double));
    
            var kichThuocPptParameter = kichThuocPpt.HasValue ?
                new ObjectParameter("KichThuocPpt", kichThuocPpt) :
                new ObjectParameter("KichThuocPpt", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DanhSachThuBai_Insert", idThuBai, idThiParameter, diemTnParameter, kichThuocWordParameter, kichThuocExcelParameter, kichThuocPptParameter);
        }
    
        public virtual int DanhSachThuBai_Update(Nullable<int> idThuBai, Nullable<int> idThi, Nullable<double> diemTn, Nullable<double> kichThuocWord, Nullable<double> kichThuocExcel, Nullable<double> kichThuocPpt)
        {
            var idThuBaiParameter = idThuBai.HasValue ?
                new ObjectParameter("IdThuBai", idThuBai) :
                new ObjectParameter("IdThuBai", typeof(int));
    
            var idThiParameter = idThi.HasValue ?
                new ObjectParameter("IdThi", idThi) :
                new ObjectParameter("IdThi", typeof(int));
    
            var diemTnParameter = diemTn.HasValue ?
                new ObjectParameter("DiemTn", diemTn) :
                new ObjectParameter("DiemTn", typeof(double));
    
            var kichThuocWordParameter = kichThuocWord.HasValue ?
                new ObjectParameter("KichThuocWord", kichThuocWord) :
                new ObjectParameter("KichThuocWord", typeof(double));
    
            var kichThuocExcelParameter = kichThuocExcel.HasValue ?
                new ObjectParameter("KichThuocExcel", kichThuocExcel) :
                new ObjectParameter("KichThuocExcel", typeof(double));
    
            var kichThuocPptParameter = kichThuocPpt.HasValue ?
                new ObjectParameter("KichThuocPpt", kichThuocPpt) :
                new ObjectParameter("KichThuocPpt", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DanhSachThuBai_Update", idThuBaiParameter, idThiParameter, diemTnParameter, kichThuocWordParameter, kichThuocExcelParameter, kichThuocPptParameter);
        }
    
        public virtual int DotThi_Delete(Nullable<int> idDotThi)
        {
            var idDotThiParameter = idDotThi.HasValue ?
                new ObjectParameter("IdDotThi", idDotThi) :
                new ObjectParameter("IdDotThi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DotThi_Delete", idDotThiParameter);
        }
    
        public virtual ObjectResult<DotThi_Find_Result> DotThi_Find(Nullable<bool> searchUsingOR, Nullable<int> idDotThi, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var idDotThiParameter = idDotThi.HasValue ?
                new ObjectParameter("IdDotThi", idDotThi) :
                new ObjectParameter("IdDotThi", typeof(int));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DotThi_Find_Result>("DotThi_Find", searchUsingORParameter, idDotThiParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<DotThi_Get_List_Result> DotThi_Get_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DotThi_Get_List_Result>("DotThi_Get_List");
        }
    
        public virtual ObjectResult<DotThi_GetByIdDotThi_Result> DotThi_GetByIdDotThi(Nullable<int> idDotThi)
        {
            var idDotThiParameter = idDotThi.HasValue ?
                new ObjectParameter("IdDotThi", idDotThi) :
                new ObjectParameter("IdDotThi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DotThi_GetByIdDotThi_Result>("DotThi_GetByIdDotThi", idDotThiParameter);
        }
    
        public virtual int DotThi_GetPaged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DotThi_GetPaged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int DotThi_Insert(ObjectParameter idDotThi, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DotThi_Insert", idDotThi, tuNgayParameter, denNgayParameter);
        }
    
        public virtual int DotThi_Update(Nullable<int> idDotThi, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var idDotThiParameter = idDotThi.HasValue ?
                new ObjectParameter("IdDotThi", idDotThi) :
                new ObjectParameter("IdDotThi", typeof(int));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DotThi_Update", idDotThiParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual int GiaoVien_Delete(Nullable<int> idGiaoVien)
        {
            var idGiaoVienParameter = idGiaoVien.HasValue ?
                new ObjectParameter("IdGiaoVien", idGiaoVien) :
                new ObjectParameter("IdGiaoVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GiaoVien_Delete", idGiaoVienParameter);
        }
    
        public virtual ObjectResult<GiaoVien_Find_Result> GiaoVien_Find(Nullable<bool> searchUsingOR, Nullable<int> idGiaoVien, string ho, string ten, string donVi, string capBac)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var idGiaoVienParameter = idGiaoVien.HasValue ?
                new ObjectParameter("IdGiaoVien", idGiaoVien) :
                new ObjectParameter("IdGiaoVien", typeof(int));
    
            var hoParameter = ho != null ?
                new ObjectParameter("Ho", ho) :
                new ObjectParameter("Ho", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var donViParameter = donVi != null ?
                new ObjectParameter("DonVi", donVi) :
                new ObjectParameter("DonVi", typeof(string));
    
            var capBacParameter = capBac != null ?
                new ObjectParameter("CapBac", capBac) :
                new ObjectParameter("CapBac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoVien_Find_Result>("GiaoVien_Find", searchUsingORParameter, idGiaoVienParameter, hoParameter, tenParameter, donViParameter, capBacParameter);
        }
    
        public virtual ObjectResult<GiaoVien_Get_List_Result> GiaoVien_Get_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoVien_Get_List_Result>("GiaoVien_Get_List");
        }
    
        public virtual ObjectResult<GiaoVien_GetByIdGiaoVien_Result> GiaoVien_GetByIdGiaoVien(Nullable<int> idGiaoVien)
        {
            var idGiaoVienParameter = idGiaoVien.HasValue ?
                new ObjectParameter("IdGiaoVien", idGiaoVien) :
                new ObjectParameter("IdGiaoVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoVien_GetByIdGiaoVien_Result>("GiaoVien_GetByIdGiaoVien", idGiaoVienParameter);
        }
    
        public virtual int GiaoVien_GetPaged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GiaoVien_GetPaged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int GiaoVien_Insert(ObjectParameter idGiaoVien, string ho, string ten, string donVi, string capBac)
        {
            var hoParameter = ho != null ?
                new ObjectParameter("Ho", ho) :
                new ObjectParameter("Ho", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var donViParameter = donVi != null ?
                new ObjectParameter("DonVi", donVi) :
                new ObjectParameter("DonVi", typeof(string));
    
            var capBacParameter = capBac != null ?
                new ObjectParameter("CapBac", capBac) :
                new ObjectParameter("CapBac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GiaoVien_Insert", idGiaoVien, hoParameter, tenParameter, donViParameter, capBacParameter);
        }
    
        public virtual int GiaoVien_Update(Nullable<int> idGiaoVien, string ho, string ten, string donVi, string capBac)
        {
            var idGiaoVienParameter = idGiaoVien.HasValue ?
                new ObjectParameter("IdGiaoVien", idGiaoVien) :
                new ObjectParameter("IdGiaoVien", typeof(int));
    
            var hoParameter = ho != null ?
                new ObjectParameter("Ho", ho) :
                new ObjectParameter("Ho", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var donViParameter = donVi != null ?
                new ObjectParameter("DonVi", donVi) :
                new ObjectParameter("DonVi", typeof(string));
    
            var capBacParameter = capBac != null ?
                new ObjectParameter("CapBac", capBac) :
                new ObjectParameter("CapBac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GiaoVien_Update", idGiaoVienParameter, hoParameter, tenParameter, donViParameter, capBacParameter);
        }
    
        public virtual int HoiDong_Delete(Nullable<int> idHoiDong)
        {
            var idHoiDongParameter = idHoiDong.HasValue ?
                new ObjectParameter("IdHoiDong", idHoiDong) :
                new ObjectParameter("IdHoiDong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HoiDong_Delete", idHoiDongParameter);
        }
    
        public virtual ObjectResult<HoiDong_Find_Result> HoiDong_Find(Nullable<bool> searchUsingOR, Nullable<int> idHoiDong, Nullable<int> idGiaoVien, Nullable<int> idDotThi, Nullable<int> idNhiemVu)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var idHoiDongParameter = idHoiDong.HasValue ?
                new ObjectParameter("IdHoiDong", idHoiDong) :
                new ObjectParameter("IdHoiDong", typeof(int));
    
            var idGiaoVienParameter = idGiaoVien.HasValue ?
                new ObjectParameter("IdGiaoVien", idGiaoVien) :
                new ObjectParameter("IdGiaoVien", typeof(int));
    
            var idDotThiParameter = idDotThi.HasValue ?
                new ObjectParameter("IdDotThi", idDotThi) :
                new ObjectParameter("IdDotThi", typeof(int));
    
            var idNhiemVuParameter = idNhiemVu.HasValue ?
                new ObjectParameter("IdNhiemVu", idNhiemVu) :
                new ObjectParameter("IdNhiemVu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoiDong_Find_Result>("HoiDong_Find", searchUsingORParameter, idHoiDongParameter, idGiaoVienParameter, idDotThiParameter, idNhiemVuParameter);
        }
    
        public virtual ObjectResult<HoiDong_Get_List_Result> HoiDong_Get_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoiDong_Get_List_Result>("HoiDong_Get_List");
        }
    
        public virtual ObjectResult<HoiDong_GetByIdDotThi_Result> HoiDong_GetByIdDotThi(Nullable<int> idDotThi)
        {
            var idDotThiParameter = idDotThi.HasValue ?
                new ObjectParameter("IdDotThi", idDotThi) :
                new ObjectParameter("IdDotThi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoiDong_GetByIdDotThi_Result>("HoiDong_GetByIdDotThi", idDotThiParameter);
        }
    
        public virtual ObjectResult<HoiDong_GetByIdGiaoVien_Result> HoiDong_GetByIdGiaoVien(Nullable<int> idGiaoVien)
        {
            var idGiaoVienParameter = idGiaoVien.HasValue ?
                new ObjectParameter("IdGiaoVien", idGiaoVien) :
                new ObjectParameter("IdGiaoVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoiDong_GetByIdGiaoVien_Result>("HoiDong_GetByIdGiaoVien", idGiaoVienParameter);
        }
    
        public virtual ObjectResult<HoiDong_GetByIdHoiDong_Result> HoiDong_GetByIdHoiDong(Nullable<int> idHoiDong)
        {
            var idHoiDongParameter = idHoiDong.HasValue ?
                new ObjectParameter("IdHoiDong", idHoiDong) :
                new ObjectParameter("IdHoiDong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoiDong_GetByIdHoiDong_Result>("HoiDong_GetByIdHoiDong", idHoiDongParameter);
        }
    
        public virtual ObjectResult<HoiDong_GetByIdNhiemVu_Result> HoiDong_GetByIdNhiemVu(Nullable<int> idNhiemVu)
        {
            var idNhiemVuParameter = idNhiemVu.HasValue ?
                new ObjectParameter("IdNhiemVu", idNhiemVu) :
                new ObjectParameter("IdNhiemVu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoiDong_GetByIdNhiemVu_Result>("HoiDong_GetByIdNhiemVu", idNhiemVuParameter);
        }
    
        public virtual int HoiDong_GetPaged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HoiDong_GetPaged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int HoiDong_Insert(ObjectParameter idHoiDong, Nullable<int> idGiaoVien, Nullable<int> idDotThi, Nullable<int> idNhiemVu)
        {
            var idGiaoVienParameter = idGiaoVien.HasValue ?
                new ObjectParameter("IdGiaoVien", idGiaoVien) :
                new ObjectParameter("IdGiaoVien", typeof(int));
    
            var idDotThiParameter = idDotThi.HasValue ?
                new ObjectParameter("IdDotThi", idDotThi) :
                new ObjectParameter("IdDotThi", typeof(int));
    
            var idNhiemVuParameter = idNhiemVu.HasValue ?
                new ObjectParameter("IdNhiemVu", idNhiemVu) :
                new ObjectParameter("IdNhiemVu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HoiDong_Insert", idHoiDong, idGiaoVienParameter, idDotThiParameter, idNhiemVuParameter);
        }
    
        public virtual int HoiDong_Update(Nullable<int> idHoiDong, Nullable<int> idGiaoVien, Nullable<int> idDotThi, Nullable<int> idNhiemVu)
        {
            var idHoiDongParameter = idHoiDong.HasValue ?
                new ObjectParameter("IdHoiDong", idHoiDong) :
                new ObjectParameter("IdHoiDong", typeof(int));
    
            var idGiaoVienParameter = idGiaoVien.HasValue ?
                new ObjectParameter("IdGiaoVien", idGiaoVien) :
                new ObjectParameter("IdGiaoVien", typeof(int));
    
            var idDotThiParameter = idDotThi.HasValue ?
                new ObjectParameter("IdDotThi", idDotThi) :
                new ObjectParameter("IdDotThi", typeof(int));
    
            var idNhiemVuParameter = idNhiemVu.HasValue ?
                new ObjectParameter("IdNhiemVu", idNhiemVu) :
                new ObjectParameter("IdNhiemVu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HoiDong_Update", idHoiDongParameter, idGiaoVienParameter, idDotThiParameter, idNhiemVuParameter);
        }
    
        public virtual int KetQua_Delete(Nullable<int> idKetQua)
        {
            var idKetQuaParameter = idKetQua.HasValue ?
                new ObjectParameter("IdKetQua", idKetQua) :
                new ObjectParameter("IdKetQua", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KetQua_Delete", idKetQuaParameter);
        }
    
        public virtual ObjectResult<KetQua_Find_Result> KetQua_Find(Nullable<bool> searchUsingOR, Nullable<int> idKetQua, Nullable<int> idThuBai, Nullable<double> diemThucHanh)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var idKetQuaParameter = idKetQua.HasValue ?
                new ObjectParameter("IdKetQua", idKetQua) :
                new ObjectParameter("IdKetQua", typeof(int));
    
            var idThuBaiParameter = idThuBai.HasValue ?
                new ObjectParameter("IdThuBai", idThuBai) :
                new ObjectParameter("IdThuBai", typeof(int));
    
            var diemThucHanhParameter = diemThucHanh.HasValue ?
                new ObjectParameter("DiemThucHanh", diemThucHanh) :
                new ObjectParameter("DiemThucHanh", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KetQua_Find_Result>("KetQua_Find", searchUsingORParameter, idKetQuaParameter, idThuBaiParameter, diemThucHanhParameter);
        }
    
        public virtual ObjectResult<KetQua_Get_List_Result> KetQua_Get_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KetQua_Get_List_Result>("KetQua_Get_List");
        }
    
        public virtual ObjectResult<KetQua_GetByIdKetQua_Result> KetQua_GetByIdKetQua(Nullable<int> idKetQua)
        {
            var idKetQuaParameter = idKetQua.HasValue ?
                new ObjectParameter("IdKetQua", idKetQua) :
                new ObjectParameter("IdKetQua", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KetQua_GetByIdKetQua_Result>("KetQua_GetByIdKetQua", idKetQuaParameter);
        }
    
        public virtual ObjectResult<KetQua_GetByIdThuBai_Result> KetQua_GetByIdThuBai(Nullable<int> idThuBai)
        {
            var idThuBaiParameter = idThuBai.HasValue ?
                new ObjectParameter("IdThuBai", idThuBai) :
                new ObjectParameter("IdThuBai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KetQua_GetByIdThuBai_Result>("KetQua_GetByIdThuBai", idThuBaiParameter);
        }
    
        public virtual int KetQua_GetPaged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KetQua_GetPaged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int KetQua_Insert(ObjectParameter idKetQua, Nullable<int> idThuBai, Nullable<double> diemThucHanh)
        {
            var idThuBaiParameter = idThuBai.HasValue ?
                new ObjectParameter("IdThuBai", idThuBai) :
                new ObjectParameter("IdThuBai", typeof(int));
    
            var diemThucHanhParameter = diemThucHanh.HasValue ?
                new ObjectParameter("DiemThucHanh", diemThucHanh) :
                new ObjectParameter("DiemThucHanh", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KetQua_Insert", idKetQua, idThuBaiParameter, diemThucHanhParameter);
        }
    
        public virtual int KetQua_Update(Nullable<int> idKetQua, Nullable<int> idThuBai, Nullable<double> diemThucHanh)
        {
            var idKetQuaParameter = idKetQua.HasValue ?
                new ObjectParameter("IdKetQua", idKetQua) :
                new ObjectParameter("IdKetQua", typeof(int));
    
            var idThuBaiParameter = idThuBai.HasValue ?
                new ObjectParameter("IdThuBai", idThuBai) :
                new ObjectParameter("IdThuBai", typeof(int));
    
            var diemThucHanhParameter = diemThucHanh.HasValue ?
                new ObjectParameter("DiemThucHanh", diemThucHanh) :
                new ObjectParameter("DiemThucHanh", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KetQua_Update", idKetQuaParameter, idThuBaiParameter, diemThucHanhParameter);
        }
    
        public virtual int LePhi_Delete(Nullable<int> idLePhi)
        {
            var idLePhiParameter = idLePhi.HasValue ?
                new ObjectParameter("IdLePhi", idLePhi) :
                new ObjectParameter("IdLePhi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LePhi_Delete", idLePhiParameter);
        }
    
        public virtual ObjectResult<LePhi_Find_Result> LePhi_Find(Nullable<bool> searchUsingOR, Nullable<int> idLePhi, Nullable<int> idNoiDung, Nullable<int> idNhuCau, Nullable<decimal> lePhi, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var idLePhiParameter = idLePhi.HasValue ?
                new ObjectParameter("IdLePhi", idLePhi) :
                new ObjectParameter("IdLePhi", typeof(int));
    
            var idNoiDungParameter = idNoiDung.HasValue ?
                new ObjectParameter("IdNoiDung", idNoiDung) :
                new ObjectParameter("IdNoiDung", typeof(int));
    
            var idNhuCauParameter = idNhuCau.HasValue ?
                new ObjectParameter("IdNhuCau", idNhuCau) :
                new ObjectParameter("IdNhuCau", typeof(int));
    
            var lePhiParameter = lePhi.HasValue ?
                new ObjectParameter("LePhi", lePhi) :
                new ObjectParameter("LePhi", typeof(decimal));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LePhi_Find_Result>("LePhi_Find", searchUsingORParameter, idLePhiParameter, idNoiDungParameter, idNhuCauParameter, lePhiParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<LePhi_Get_List_Result> LePhi_Get_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LePhi_Get_List_Result>("LePhi_Get_List");
        }
    
        public virtual ObjectResult<LePhi_GetByIdLePhi_Result> LePhi_GetByIdLePhi(Nullable<int> idLePhi)
        {
            var idLePhiParameter = idLePhi.HasValue ?
                new ObjectParameter("IdLePhi", idLePhi) :
                new ObjectParameter("IdLePhi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LePhi_GetByIdLePhi_Result>("LePhi_GetByIdLePhi", idLePhiParameter);
        }
    
        public virtual ObjectResult<LePhi_GetByIdNhuCau_Result> LePhi_GetByIdNhuCau(Nullable<int> idNhuCau)
        {
            var idNhuCauParameter = idNhuCau.HasValue ?
                new ObjectParameter("IdNhuCau", idNhuCau) :
                new ObjectParameter("IdNhuCau", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LePhi_GetByIdNhuCau_Result>("LePhi_GetByIdNhuCau", idNhuCauParameter);
        }
    
        public virtual ObjectResult<LePhi_GetByIdNoiDung_Result> LePhi_GetByIdNoiDung(Nullable<int> idNoiDung)
        {
            var idNoiDungParameter = idNoiDung.HasValue ?
                new ObjectParameter("IdNoiDung", idNoiDung) :
                new ObjectParameter("IdNoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LePhi_GetByIdNoiDung_Result>("LePhi_GetByIdNoiDung", idNoiDungParameter);
        }
    
        public virtual int LePhi_GetPaged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LePhi_GetPaged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int LePhi_Insert(ObjectParameter idLePhi, Nullable<int> idNoiDung, Nullable<int> idNhuCau, Nullable<decimal> lePhi, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var idNoiDungParameter = idNoiDung.HasValue ?
                new ObjectParameter("IdNoiDung", idNoiDung) :
                new ObjectParameter("IdNoiDung", typeof(int));
    
            var idNhuCauParameter = idNhuCau.HasValue ?
                new ObjectParameter("IdNhuCau", idNhuCau) :
                new ObjectParameter("IdNhuCau", typeof(int));
    
            var lePhiParameter = lePhi.HasValue ?
                new ObjectParameter("LePhi", lePhi) :
                new ObjectParameter("LePhi", typeof(decimal));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LePhi_Insert", idLePhi, idNoiDungParameter, idNhuCauParameter, lePhiParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual int LePhi_Update(Nullable<int> idLePhi, Nullable<int> idNoiDung, Nullable<int> idNhuCau, Nullable<decimal> lePhi, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var idLePhiParameter = idLePhi.HasValue ?
                new ObjectParameter("IdLePhi", idLePhi) :
                new ObjectParameter("IdLePhi", typeof(int));
    
            var idNoiDungParameter = idNoiDung.HasValue ?
                new ObjectParameter("IdNoiDung", idNoiDung) :
                new ObjectParameter("IdNoiDung", typeof(int));
    
            var idNhuCauParameter = idNhuCau.HasValue ?
                new ObjectParameter("IdNhuCau", idNhuCau) :
                new ObjectParameter("IdNhuCau", typeof(int));
    
            var lePhiParameter = lePhi.HasValue ?
                new ObjectParameter("LePhi", lePhi) :
                new ObjectParameter("LePhi", typeof(decimal));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LePhi_Update", idLePhiParameter, idNoiDungParameter, idNhuCauParameter, lePhiParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual int NhiemVu_Delete(Nullable<int> idNhiemVu)
        {
            var idNhiemVuParameter = idNhiemVu.HasValue ?
                new ObjectParameter("IdNhiemVu", idNhiemVu) :
                new ObjectParameter("IdNhiemVu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhiemVu_Delete", idNhiemVuParameter);
        }
    
        public virtual ObjectResult<NhiemVu_Find_Result> NhiemVu_Find(Nullable<bool> searchUsingOR, Nullable<int> idNhiemVu, string tenNhiemVu, string ghiChu)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var idNhiemVuParameter = idNhiemVu.HasValue ?
                new ObjectParameter("IdNhiemVu", idNhiemVu) :
                new ObjectParameter("IdNhiemVu", typeof(int));
    
            var tenNhiemVuParameter = tenNhiemVu != null ?
                new ObjectParameter("TenNhiemVu", tenNhiemVu) :
                new ObjectParameter("TenNhiemVu", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhiemVu_Find_Result>("NhiemVu_Find", searchUsingORParameter, idNhiemVuParameter, tenNhiemVuParameter, ghiChuParameter);
        }
    
        public virtual ObjectResult<NhiemVu_Get_List_Result> NhiemVu_Get_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhiemVu_Get_List_Result>("NhiemVu_Get_List");
        }
    
        public virtual ObjectResult<NhiemVu_GetByIdNhiemVu_Result> NhiemVu_GetByIdNhiemVu(Nullable<int> idNhiemVu)
        {
            var idNhiemVuParameter = idNhiemVu.HasValue ?
                new ObjectParameter("IdNhiemVu", idNhiemVu) :
                new ObjectParameter("IdNhiemVu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhiemVu_GetByIdNhiemVu_Result>("NhiemVu_GetByIdNhiemVu", idNhiemVuParameter);
        }
    
        public virtual int NhiemVu_GetPaged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhiemVu_GetPaged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int NhiemVu_Insert(ObjectParameter idNhiemVu, string tenNhiemVu, string ghiChu)
        {
            var tenNhiemVuParameter = tenNhiemVu != null ?
                new ObjectParameter("TenNhiemVu", tenNhiemVu) :
                new ObjectParameter("TenNhiemVu", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhiemVu_Insert", idNhiemVu, tenNhiemVuParameter, ghiChuParameter);
        }
    
        public virtual int NhiemVu_Update(Nullable<int> idNhiemVu, string tenNhiemVu, string ghiChu)
        {
            var idNhiemVuParameter = idNhiemVu.HasValue ?
                new ObjectParameter("IdNhiemVu", idNhiemVu) :
                new ObjectParameter("IdNhiemVu", typeof(int));
    
            var tenNhiemVuParameter = tenNhiemVu != null ?
                new ObjectParameter("TenNhiemVu", tenNhiemVu) :
                new ObjectParameter("TenNhiemVu", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhiemVu_Update", idNhiemVuParameter, tenNhiemVuParameter, ghiChuParameter);
        }
    
        public virtual int NhuCau_Delete(Nullable<int> idNhuCau)
        {
            var idNhuCauParameter = idNhuCau.HasValue ?
                new ObjectParameter("IdNhuCau", idNhuCau) :
                new ObjectParameter("IdNhuCau", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhuCau_Delete", idNhuCauParameter);
        }
    
        public virtual ObjectResult<NhuCau_Find_Result> NhuCau_Find(Nullable<bool> searchUsingOR, Nullable<int> idNhuCau, string nhuCau)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var idNhuCauParameter = idNhuCau.HasValue ?
                new ObjectParameter("IdNhuCau", idNhuCau) :
                new ObjectParameter("IdNhuCau", typeof(int));
    
            var nhuCauParameter = nhuCau != null ?
                new ObjectParameter("NhuCau", nhuCau) :
                new ObjectParameter("NhuCau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhuCau_Find_Result>("NhuCau_Find", searchUsingORParameter, idNhuCauParameter, nhuCauParameter);
        }
    
        public virtual ObjectResult<NhuCau_Get_List_Result> NhuCau_Get_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhuCau_Get_List_Result>("NhuCau_Get_List");
        }
    
        public virtual ObjectResult<NhuCau_GetByIdNhuCau_Result> NhuCau_GetByIdNhuCau(Nullable<int> idNhuCau)
        {
            var idNhuCauParameter = idNhuCau.HasValue ?
                new ObjectParameter("IdNhuCau", idNhuCau) :
                new ObjectParameter("IdNhuCau", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhuCau_GetByIdNhuCau_Result>("NhuCau_GetByIdNhuCau", idNhuCauParameter);
        }
    
        public virtual int NhuCau_GetPaged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhuCau_GetPaged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int NhuCau_Insert(ObjectParameter idNhuCau, string nhuCau)
        {
            var nhuCauParameter = nhuCau != null ?
                new ObjectParameter("NhuCau", nhuCau) :
                new ObjectParameter("NhuCau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhuCau_Insert", idNhuCau, nhuCauParameter);
        }
    
        public virtual int NhuCau_Update(Nullable<int> idNhuCau, string nhuCau)
        {
            var idNhuCauParameter = idNhuCau.HasValue ?
                new ObjectParameter("IdNhuCau", idNhuCau) :
                new ObjectParameter("IdNhuCau", typeof(int));
    
            var nhuCauParameter = nhuCau != null ?
                new ObjectParameter("NhuCau", nhuCau) :
                new ObjectParameter("NhuCau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhuCau_Update", idNhuCauParameter, nhuCauParameter);
        }
    
        public virtual int NoiDung_Delete(Nullable<int> idNoiDung)
        {
            var idNoiDungParameter = idNoiDung.HasValue ?
                new ObjectParameter("IdNoiDung", idNoiDung) :
                new ObjectParameter("IdNoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NoiDung_Delete", idNoiDungParameter);
        }
    
        public virtual ObjectResult<NoiDung_Find_Result> NoiDung_Find(Nullable<bool> searchUsingOR, Nullable<int> idNoiDung, string doiTuong, string noiDung)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var idNoiDungParameter = idNoiDung.HasValue ?
                new ObjectParameter("IdNoiDung", idNoiDung) :
                new ObjectParameter("IdNoiDung", typeof(int));
    
            var doiTuongParameter = doiTuong != null ?
                new ObjectParameter("DoiTuong", doiTuong) :
                new ObjectParameter("DoiTuong", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NoiDung_Find_Result>("NoiDung_Find", searchUsingORParameter, idNoiDungParameter, doiTuongParameter, noiDungParameter);
        }
    
        public virtual ObjectResult<NoiDung_Get_List_Result> NoiDung_Get_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NoiDung_Get_List_Result>("NoiDung_Get_List");
        }
    
        public virtual ObjectResult<NoiDung_GetByIdNoiDung_Result> NoiDung_GetByIdNoiDung(Nullable<int> idNoiDung)
        {
            var idNoiDungParameter = idNoiDung.HasValue ?
                new ObjectParameter("IdNoiDung", idNoiDung) :
                new ObjectParameter("IdNoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NoiDung_GetByIdNoiDung_Result>("NoiDung_GetByIdNoiDung", idNoiDungParameter);
        }
    
        public virtual int NoiDung_GetPaged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NoiDung_GetPaged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int NoiDung_Insert(ObjectParameter idNoiDung, string doiTuong, string noiDung)
        {
            var doiTuongParameter = doiTuong != null ?
                new ObjectParameter("DoiTuong", doiTuong) :
                new ObjectParameter("DoiTuong", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NoiDung_Insert", idNoiDung, doiTuongParameter, noiDungParameter);
        }
    
        public virtual int NoiDung_Update(Nullable<int> idNoiDung, string doiTuong, string noiDung)
        {
            var idNoiDungParameter = idNoiDung.HasValue ?
                new ObjectParameter("IdNoiDung", idNoiDung) :
                new ObjectParameter("IdNoiDung", typeof(int));
    
            var doiTuongParameter = doiTuong != null ?
                new ObjectParameter("DoiTuong", doiTuong) :
                new ObjectParameter("DoiTuong", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NoiDung_Update", idNoiDungParameter, doiTuongParameter, noiDungParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int ThiSinh_Delete(Nullable<int> idThiSinh)
        {
            var idThiSinhParameter = idThiSinh.HasValue ?
                new ObjectParameter("IdThiSinh", idThiSinh) :
                new ObjectParameter("IdThiSinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThiSinh_Delete", idThiSinhParameter);
        }
    
        public virtual ObjectResult<ThiSinh_Find_Result> ThiSinh_Find(Nullable<bool> searchUsingOR, Nullable<int> idThiSinh, string email, string ho, string ten, Nullable<System.DateTime> ngaySinh, Nullable<bool> gioiTinh, string cmnd, string sdt, Nullable<int> idNoiDung, Nullable<int> idNhuCau, Nullable<bool> trangThai)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var idThiSinhParameter = idThiSinh.HasValue ?
                new ObjectParameter("IdThiSinh", idThiSinh) :
                new ObjectParameter("IdThiSinh", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var hoParameter = ho != null ?
                new ObjectParameter("Ho", ho) :
                new ObjectParameter("Ho", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var cmndParameter = cmnd != null ?
                new ObjectParameter("Cmnd", cmnd) :
                new ObjectParameter("Cmnd", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            var idNoiDungParameter = idNoiDung.HasValue ?
                new ObjectParameter("IdNoiDung", idNoiDung) :
                new ObjectParameter("IdNoiDung", typeof(int));
    
            var idNhuCauParameter = idNhuCau.HasValue ?
                new ObjectParameter("IdNhuCau", idNhuCau) :
                new ObjectParameter("IdNhuCau", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThiSinh_Find_Result>("ThiSinh_Find", searchUsingORParameter, idThiSinhParameter, emailParameter, hoParameter, tenParameter, ngaySinhParameter, gioiTinhParameter, cmndParameter, sdtParameter, idNoiDungParameter, idNhuCauParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<ThiSinh_Get_List_Result> ThiSinh_Get_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThiSinh_Get_List_Result>("ThiSinh_Get_List");
        }
    
        public virtual ObjectResult<ThiSinh_GetByIdNhuCau_Result> ThiSinh_GetByIdNhuCau(Nullable<int> idNhuCau)
        {
            var idNhuCauParameter = idNhuCau.HasValue ?
                new ObjectParameter("IdNhuCau", idNhuCau) :
                new ObjectParameter("IdNhuCau", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThiSinh_GetByIdNhuCau_Result>("ThiSinh_GetByIdNhuCau", idNhuCauParameter);
        }
    
        public virtual ObjectResult<ThiSinh_GetByIdNoiDung_Result> ThiSinh_GetByIdNoiDung(Nullable<int> idNoiDung)
        {
            var idNoiDungParameter = idNoiDung.HasValue ?
                new ObjectParameter("IdNoiDung", idNoiDung) :
                new ObjectParameter("IdNoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThiSinh_GetByIdNoiDung_Result>("ThiSinh_GetByIdNoiDung", idNoiDungParameter);
        }
    
        public virtual ObjectResult<ThiSinh_GetByIdThiSinh_Result> ThiSinh_GetByIdThiSinh(Nullable<int> idThiSinh)
        {
            var idThiSinhParameter = idThiSinh.HasValue ?
                new ObjectParameter("IdThiSinh", idThiSinh) :
                new ObjectParameter("IdThiSinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThiSinh_GetByIdThiSinh_Result>("ThiSinh_GetByIdThiSinh", idThiSinhParameter);
        }
    
        public virtual int ThiSinh_GetPaged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThiSinh_GetPaged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int ThiSinh_Insert(ObjectParameter idThiSinh, string email, string ho, string ten, Nullable<System.DateTime> ngaySinh, Nullable<bool> gioiTinh, string cmnd, string sdt, Nullable<int> idNoiDung, Nullable<int> idNhuCau, Nullable<bool> trangThai)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var hoParameter = ho != null ?
                new ObjectParameter("Ho", ho) :
                new ObjectParameter("Ho", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var cmndParameter = cmnd != null ?
                new ObjectParameter("Cmnd", cmnd) :
                new ObjectParameter("Cmnd", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            var idNoiDungParameter = idNoiDung.HasValue ?
                new ObjectParameter("IdNoiDung", idNoiDung) :
                new ObjectParameter("IdNoiDung", typeof(int));
    
            var idNhuCauParameter = idNhuCau.HasValue ?
                new ObjectParameter("IdNhuCau", idNhuCau) :
                new ObjectParameter("IdNhuCau", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThiSinh_Insert", idThiSinh, emailParameter, hoParameter, tenParameter, ngaySinhParameter, gioiTinhParameter, cmndParameter, sdtParameter, idNoiDungParameter, idNhuCauParameter, trangThaiParameter);
        }
    
        public virtual int ThiSinh_Update(Nullable<int> idThiSinh, string email, string ho, string ten, Nullable<System.DateTime> ngaySinh, Nullable<bool> gioiTinh, string cmnd, string sdt, Nullable<int> idNoiDung, Nullable<int> idNhuCau, Nullable<bool> trangThai)
        {
            var idThiSinhParameter = idThiSinh.HasValue ?
                new ObjectParameter("IdThiSinh", idThiSinh) :
                new ObjectParameter("IdThiSinh", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var hoParameter = ho != null ?
                new ObjectParameter("Ho", ho) :
                new ObjectParameter("Ho", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var cmndParameter = cmnd != null ?
                new ObjectParameter("Cmnd", cmnd) :
                new ObjectParameter("Cmnd", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            var idNoiDungParameter = idNoiDung.HasValue ?
                new ObjectParameter("IdNoiDung", idNoiDung) :
                new ObjectParameter("IdNoiDung", typeof(int));
    
            var idNhuCauParameter = idNhuCau.HasValue ?
                new ObjectParameter("IdNhuCau", idNhuCau) :
                new ObjectParameter("IdNhuCau", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThiSinh_Update", idThiSinhParameter, emailParameter, hoParameter, tenParameter, ngaySinhParameter, gioiTinhParameter, cmndParameter, sdtParameter, idNoiDungParameter, idNhuCauParameter, trangThaiParameter);
        }
    }
}
