//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongBan
    {
        public string MaPB { get; set; }
        public string TenPB { get; set; }
        public string DiaDiem { get; set; }
        public string MaTP { get; set; }
        public Nullable<System.DateTime> NgayNhanChuc { get; set; }
    }
}
